# Data Preprocessing

In [1]:
# Import necessary Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#Import the dataset
dataset = pd.read_csv('DataSet.csv')

In [3]:
dataset

Developer   Age   Salary Married
0   Karachi  42.0  78000.0      No
1    Lahore  32.0  48000.0     Yes
2   Karachi  36.0  60000.0      No
3    Multan  41.0  68000.0      No
4    Lahore  42.0      NaN     Yes
5    Multan  43.0  59000.0     Yes
6   Karachi   NaN  59000.0      No
7    Lahore  44.0  79000.0     Yes
8    Multan  52.0  99000.0      No
9    Lahore  32.0  69000.0     Yes

In [7]:
X=dataset.iloc[:,:-1].values

y = dataset.iloc[:, 3]

In [10]:
#Missing Value Handling by MEAN

from sklearn.impute import SimpleImputer

imputer =SimpleImputer(missing_values=np.nan, strategy='mean')

imputer=imputer.fit(X[:,1:3])

X[:,1:3]= imputer.transform(X[:,1:3])

# You can also handle missing values by median & most_frequent

In [11]:
X[:,1:3]

array([[42.0, 78000.0],
       [32.0, 48000.0],
       [36.0, 60000.0],
       [41.0, 68000.0],
       [42.0, 68777.77777777778],
       [43.0, 59000.0],
       [40.44444444444444, 59000.0],
       [44.0, 79000.0],
       [52.0, 99000.0],
       [32.0, 69000.0]], dtype=object)

In [13]:
#Concept of Dummy Variable, Handling the conflict of them

from sklearn.preprocessing import LabelEncoder, OneHotEncoder

labelencoder_X = LabelEncoder()

X[:,0]=labelencoder_X.fit_transform(X[:,0])

onehotencoder=OneHotEncoder()

X=onehotencoder.fit_transform(X).toarray()

In [15]:
X

array([[1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0.],
       [0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 1.],
       [0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0.]])

In [16]:
#Training and Testing Data (divide the data into two part)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test =train_test_split(X,y,test_size=0.2, random_state=0)

In [17]:
#Standard and fit the data for better predication 

from sklearn.preprocessing import StandardScaler

sc_X=StandardScaler()

X_test=sc_X.fit_transform(X_test)


X_train=sc_X.fit_transform(X_train)

In [18]:
X_train

array([[-0.57735027,  1.        , -0.57735027, -0.57735027,  0.        ,
        -0.37796447, -0.37796447,  1.73205081, -0.37796447, -0.37796447,
         0.        , -0.37796447, -0.57735027,  0.        , -0.37796447,
         2.64575131, -0.37796447, -0.37796447, -0.37796447,  0.        ],
       [-0.57735027,  1.        , -0.57735027,  1.73205081,  0.        ,
        -0.37796447, -0.37796447, -0.57735027, -0.37796447, -0.37796447,
         0.        , -0.37796447, -0.57735027,  0.        , -0.37796447,
        -0.37796447,  2.64575131, -0.37796447, -0.37796447,  0.        ],
       [-0.57735027,  1.        , -0.57735027,  1.73205081,  0.        ,
        -0.37796447, -0.37796447, -0.57735027, -0.37796447, -0.37796447,
         0.        ,  2.64575131, -0.57735027,  0.        , -0.37796447,
        -0.37796447, -0.37796447, -0.37796447, -0.37796447,  0.        ],
       [ 1.73205081, -1.        , -0.57735027, -0.57735027,  0.        ,
         2.64575131, -0.37796447, -0.57735027, -

In [19]:
X_test

array([[ 1.,  0., -1.,  0.,  1.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  0.,
         1.,  0.,  0.,  0.,  0.,  0., -1.],
       [-1.,  0.,  1.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
        -1.,  0.,  0.,  0.,  0.,  0.,  1.]])