# Time Series Method

In [3]:
# Import necessary libraries
import numpy as np
from sklearn.model_selection import TimeSeriesSplit

In [4]:
# Create Dependent and Independent Variables
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([1, 2, 3, 4, 5, 6])

In [5]:
# Create Time Series object
tscv = TimeSeriesSplit(n_splits=3,max_train_size= None)
print(tscv)  

TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None)


In [6]:
for train, test in tscv.split(X):
    print("%s %s" % (train, test))  

[0 1 2] [3]
[0 1 2 3] [4]
[0 1 2 3 4] [5]
